# Generated by Django 5.2.8 on 2025-11-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='cook',
        ),
    ]
